_target_: deepscreen.models.components.cnn_deepdta.CNN_DeepDTA

max_sequence_length: ${datamodule.protein_featurizer.max_sequence_length}
filters: [32, 64, 96]
kernels: [4, 8, 12]
in_channels: ${datamodule.protein_featurizer.in_channels}
out_channels: 128