_target_: deepscreen.models.components.cnn_deepdta.CNN_DeepDTA

max_sequence_length: ${datamodule.drug_featurizer.max_sequence_length}
filters: [32, 64, 96]
kernels: [4, 6, 8]
in_channels: ${datamodule.drug_featurizer.in_channels}
out_channels: 128