_target_: deepscreen.models.components.transformer

input_dim: 1024
emb_size: 128
max_position_size: 50
dropout: 0.1
n_layer: 8
intermediate_size: 512
num_attention_heads: 8
attention_probs_dropout: 0.1
hidden_dropout: 0.1